version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # Actions mudam pouco, checar mensalmente basta.

  # 2. Verifica o Python 
  - package-ecosystem: "pip"
    directory: "/integralizei-backend"
    schedule:
      interval: "weekly" # Checa toda semana
    open-pull-requests-limit: 5

  # 3. Verifica o JavaScript 
  - package-ecosystem: "npm"
    directory: "/integralizei-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # 4. Verifica o JavaScript (Backend)
  - package-ecosystem: "npm"
    directory: "/integralizei-backend"
    schedule:
      interval: "weekly"