services:
  # -------------------------------------------------------
  # Serviço 1: API Python (Core) - Porta 5000
  # -------------------------------------------------------
  backend-python:
    build: 
      context: ./integralizei-backend
      dockerfile: Dockerfile
    container_name: integralizei-core
    ports:
      - "5000:5000"
    volumes:
      - ./integralizei-backend:/app
      - ./integralizei-backend/formulario-flask/instance:/app/formulario-flask/instance
    environment:
      - FLASK_DEBUG=1
      - DB_PATH=/app/formulario-flask/instance/integralizei.db
  # -------------------------------------------------------
  # Serviço 2: API Login (Node) - Porta 3001
  # -------------------------------------------------------
  backend-login:
    build:
      context: ./integralizei-backend/login-service
      dockerfile: Dockerfile
    container_name: integralizei-auth
    ports:
      - "3001:3001"
    volumes:
      - ./integralizei-backend/login-service:/app
      - /app/node_modules
      - ./integralizei-backend/formulario-flask/instance:/app/db-shared
    environment:
      - PORT=3001
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=file:/app/db-shared/integralizei.db
      

  # -------------------------------------------------------
  # Serviço 3: Frontend (Next.js) - Porta 3000
  # -------------------------------------------------------
  frontend:
    build: ./integralizei-frontend
    container_name: integralizei-front
    ports:
      - "3000:3000"
    volumes:
      - ./integralizei-frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_AUTH_URL=http://localhost:3001
    depends_on:
      - backend-python
      - backend-login

  # -------------------------------------------------------
  # Serviço 4: Banco de Dados (Preparado para Postgres)
  # -------------------------------------------------------

  services:
  db:
    image: postgres:16
    container_name: integralizei_postgres
    environment:
      POSTGRES_USER: integralizei_usuario
      POSTGRES_PASSWORD: intgr2501
      POSTGRES_DB: integralizei_db
    ports:
      - "5432:5432"
    volumes:
      - integralizei_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: integralizei_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@meuservidor.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  integralizei_pg_data: