services:
  # -------------------------------------------------------
  # Serviço 1: API Python (Core) - Porta 5000
  # -------------------------------------------------------
  backend-python:
    build: 
      context: ./integralizei-backend
      dockerfile: Dockerfile
    container_name: integralizei-core
    ports:
      - "5000:5000"
    volumes:
      - ./integralizei-backend:/app
      - ./integralizei-backend/formulario-flask/instance:/app/formulario-flask/instance
    environment:
      - FLASK_DEBUG=1
      - DB_PATH=/app/formulario-flask/instance/integralizei.db
  # -------------------------------------------------------
  # Serviço 2: API Login (Node) - Porta 3001
  # -------------------------------------------------------
  backend-login:
    build:
      context: ./integralizei-backend/login-service
      dockerfile: Dockerfile
    container_name: integralizei-auth
    ports:
      - "3001:3001"
    volumes:
      - ./integralizei-backend/login-service:/app
      - /app/node_modules
      - ./integralizei-backend/formulario-flask/instance:/app/db-shared
    environment:
      - PORT=3001
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=file:/app/db-shared/integralizei.db
      

  # -------------------------------------------------------
  # Serviço 3: Frontend (Next.js) - Porta 3000
  # -------------------------------------------------------
  frontend:
    build: ./integralizei-frontend
    container_name: integralizei-front
    ports:
      - "3000:3000"
    volumes:
      - ./integralizei-frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_AUTH_URL=http://localhost:3001
    depends_on:
      - backend-python
      - backend-login

  # -------------------------------------------------------
  # Serviço 4: Banco de Dados (Preparado para Postgres)
  # -------------------------------------------------------

  db:
    image: postgres:15-alpine
    container_name: integralizei-db
    restart: always
    ports:
      - "5432:5432" # Libera a porta para você acessar via DBeaver/PgAdmin
    environment:
      - POSTGRES_USER=${POSTGRES_USER}         
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

# --- O FINAL DO ARQUIVO ---
volumes:
  postgres_data: