name: Testes JavaScript 

on:
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    name: Testes (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies (Frontend)
        run: npm install
        working-directory: ./integralizei-frontend
      - name: Run tests (Frontend)
        run: npm test
        working-directory: ./integralizei-frontend


  test-backend:
    name: Testes (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies (Backend)
        run: npm install
        working-directory: ./integralizei-backend 
      - name: Run tests (Backend)
        run: npm test
        working-directory: ./integralizei-backend

  
  lint-javascript:
    name: JavaScript Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Lint (Frontend)
        run: |
          npm install
          npm run lint 
        working-directory: ./integralizei-frontend

      - name: Install & Lint (Backend)
        run: |
          npm install
          npm run lint 
        working-directory: ./integralizei-backend